// <auto-generated />
using System;
using Code360_Management.Models.Students;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Code360_Management.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200225152138_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Code360_Management.Models.Guarantors.Guarantor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<int>("Nationality")
                        .HasColumnType("int");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<int>("_student_id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Guarantors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "20 wawe park",
                            FirstName = "Ekueme",
                            Gender = 0,
                            LastName = "Jonathan",
                            MaritalStatus = 0,
                            Nationality = 0,
                            Phone = 902345432L,
                            _student_id = 0
                        });
                });

            modelBuilder.Entity("Code360_Management.Models.Students.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddmissionType")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BVN")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<int>("Nationality")
                        .HasColumnType("int");

                    b.Property<string>("NextOfKinDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextOfKinEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextOfKinName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NextOfKinPhone")
                        .HasColumnType("bigint");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 5,
                            AddmissionType = 1,
                            BVN = 0L,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cokar@gmail.com",
                            FirstName = "Cokar",
                            Gender = 0,
                            LastName = "Segun",
                            MaritalStatus = 0,
                            Nationality = 0,
                            NextOfKinPhone = 0L,
                            Phone = 9074778383L
                        },
                        new
                        {
                            ID = 6,
                            AddmissionType = 0,
                            BVN = 0L,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "georgeebisike@gmail.com",
                            FirstName = "Ebisike",
                            Gender = 0,
                            LastName = "George",
                            MaritalStatus = 0,
                            Nationality = 0,
                            NextOfKinPhone = 0L,
                            Phone = 9074778383L
                        },
                        new
                        {
                            ID = 7,
                            AddmissionType = 1,
                            BVN = 0L,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pelumi@gmail.com",
                            FirstName = "Pelumi",
                            Gender = 1,
                            LastName = "Temi",
                            MaritalStatus = 0,
                            Nationality = 0,
                            NextOfKinPhone = 0L,
                            Phone = 9074778383L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
